### ISSUE TITLE
Plugin installer failed to activate engine

### ISSUE THREAD

**Issue by dws122** [bizbudding/mai-pro-engine#49]
deactivated theme
activated genesis
deactivated Mai Pro Engine
deleted Mai Pro Engine
activated them
theme installed plugin, but did not activate it

![default](https://cloud.githubusercontent.com/assets/12969150/26730522/40cc4170-477f-11e7-8b8d-091a01907ebb.png)
![plugins_ _ _wordpress](https://cloud.githubusercontent.com/assets/12969150/26730530/4af01744-477f-11e7-88ba-927ac0fadb0d.png)

**Comment by JiveDig** [comment]
refresh an admin page (maybe the Plugins page?) does that do it?

**Comment by JiveDig** [comment]
Why delete the plugin? That's a bit of an edge case, but still worth checking out.

**Comment by dws122** [comment]
refresh admin page, viewing site, viewing plugins folder, viewing site -- all did not activate.
had to manually.
@christiebizbudding indicated this has happened to her a couple times. 

Old version of the plugin was installed. Needed to delete in order to have the them install the new version.

**Comment by JiveDig** [comment]
@christiebizbudding happened during install, or when trying to manually force a new plugin delete/download/install?

**Comment by JiveDig** [comment]
I just checked kovalev's theme and it's using the old version of Mai Pro theme, which had the wrong (old) plugin name/slug
`"slug": "maitheme-engine/maitheme-engine.php",`

I'll update it there. The current version should me mai-pro-engine.

I'm guessing any issues are from sites still running Mai Pro theme version with the old engine name.

**Comment by JiveDig** [comment]
Yep. Kovalev's had the old theme and was installing maitheme-engine. All updated now and should be good from here on. I'm gonna close this. Re-open if any related issues.
