### ISSUE TITLE
text on white background with no styling appears white with shadow in the sections template

### ISSUE THREAD

**Issue by christiebizbudding** [bizbudding/mai-pro-engine#53]
![i_reclaim_my_health_today_-_reclaimers_of_health](https://user-images.githubusercontent.com/25107329/26898830-39d48006-4b9b-11e7-9218-f055cc845eb0.png)
![edit_page_ _reclaimers_of_health_ _wordpress](https://user-images.githubusercontent.com/25107329/26898858-4cd8beec-4b9b-11e7-820f-9da1da50da45.png)

**Comment by JiveDig** [comment]
Try to include live links anywhere you can, in all issues and Basecamp stuff please :)

**Comment by christiebizbudding** [comment]
Sorry! 

https://staging1.reclaimersofhealth.com/

**Comment by JiveDig** [comment]
Did you set the Background Color to white via the color picker? Or left it blank? 

Somehow it's adding the `light-content` class to the section

**Comment by christiebizbudding** [comment]
left it blank. It was fine until I added the next section below it with the blueberries and the inner styling. Then it showed up, removed the entire blueberry section and has stayed that way

**Comment by christiebizbudding** [comment]
Doing it on the section below blueberries that was just added. (section4)

**Comment by JiveDig** [comment]
Fixed in beta.13.
