### ISSUE TITLE
Hide featured image unchecks after updating page

### ISSUE THREAD

**Issue by christiebizbudding** [bizbudding/mai-pro-engine#58]
https://staging1.reclaimersofhealth.com/about/kimberly/

Attempted to recreate issue with Gretchen's page...
Screenshots before I touched anything
![gretchen_-_reclaimers_of_health](https://user-images.githubusercontent.com/25107329/26985749-e7dd07fe-4d12-11e7-9f15-cff13135b7b1.png)
![edit_page_ _reclaimers_of_health_ _wordpress](https://user-images.githubusercontent.com/25107329/26985757-ee32ed08-4d12-11e7-9e1b-43ef2c1b5bd2.png)

Hit update page..
![edit_page_ _reclaimers_of_health_ _wordpress](https://user-images.githubusercontent.com/25107329/26985794-1260baac-4d13-11e7-8dab-7aec3d0808ed.png)
![gretchen_-_reclaimers_of_health](https://user-images.githubusercontent.com/25107329/26985801-176dba36-4d13-11e7-934d-5e9ae10422d1.png)

The Hide Featured Image unchecks itself, but the featured images are hidden now - where as when the Hide Featured Image was checked, the FI was showing.

**Comment by JiveDig** [comment]
What beta version of Engine?

**Comment by christiebizbudding** [comment]
22

**Comment by JiveDig** [comment]
Fixed https://github.com/bizbudding/mai-pro-engine/commit/646033faf492f82a310c1e47e6235000548bb89d beta 23
