### ISSUE TITLE
Primary Navigation is centering always

### ISSUE THREAD

**Issue by christiebizbudding** [bizbudding/mai-pro-engine#59]
Regardless of logo placement, primary nav stays centered

**Comment by JiveDig** [comment]
You don't have a search icon in that nav menu, do you?

**Comment by christiebizbudding** [comment]
It's in the header right menu

**Comment by JiveDig** [comment]
Should be fixed with https://github.com/bizbudding/mai-pro-engine/commit/68fa156a13f2bb78c5ee39cc513ce2648daa49ca beta 24
